In [99]:
import io, csv, sys
import sys
import pandas as pd
import numpy as np
df['이동거리'] = df['이동거리'].astype(np.float64)

df = pd.read_csv('data_week.csv')

In [100]:
df.dropna(subset=['성별'], inplace=True)
df['성별'] = df['성별'].str.upper()

# temp = np.array(df['성별'].unique())

In [101]:
mean = df['이동거리'].mean()
std = df['이동거리'].std()
cutoff_lower = mean - std * 3
cutoff_upper = mean + std * 3

In [102]:
df = df[df['이동거리'] >= cutoff_lower]
df = df[df['이동거리'] <= cutoff_upper]

In [103]:
df

,대여일자,대여시간,대여소번호,대여소명,대여구분코드,성별,연령대코드,이용건수,운동량,탄소량,이동거리,사용시간
134,2021-01-01,0,1952,1952. 천왕연지타운2단지 앞,정기권,F,~10대,1,22.15,0.20,860.60,6
135,2021-01-01,0,828,828. 숙대입구역 8번,정기권,F,20대,1,0.00,0.00,0.00,41
136,2021-01-01,0,1047,1047. 건강보험 강동지사kt,정기권,F,20대,1,27.13,0.32,1370.00,12
137,2021-01-01,0,112,112. 극동방송국 앞,정기권,F,20대,1,0.00,0.00,0.00,70
138,2021-01-01,0,2620,2620. 송파나루역 4번 출구옆,정기권,F,20대,1,0.00,0.00,0.00,20
...,...,...,...,...,...,...,...,...,...,...,...,...
139068,2021-01-06,23,2189,2189.삼성서비스센터(관악점),일일권,F,60대,1,62.18,0.43,1847.25,17
139069,2021-01-06,23,2016,2016. 신대방삼거리역 3번출구쪽,일일권,M,20대,1,56.86,0.51,2209.07,18
139070,2021-01-06,23,725,725. 양강중학교앞 교차로,일일권,M,20대,1,44.00,0.35,1521.90,15
139071,2021-01-06,23,2220,2220. 반포본동 주민센터 앞,일일권,M,30대,1,60.80,0.45,1919.20,19
139072,2021-01-06,23,2319,2319. 포스코사거리 서측(수협 삼성동 지점),일일권,M,50대,1,0.00,0.00,0.00,6

In [104]:
print(df["이동거리"].describe())

count    76397.000000
mean      1859.386324
std       2461.977919
min          0.000000
25%          0.000000
50%       1040.120000
75%       2482.840000
max      13614.690000
Name: 이동거리, dtype: float64