In [11]:
import io, csv, sys
import sys
import pandas as pd
import numpy as np

# csv_reader = csv.reader(sys.stdin)
# data = [row for row in csv_reader]
# df = pd.DataFrame(data[1:], columns=data[0])
# df.replace("", np.nan, inplace=True)

In [12]:
df = pd.read_csv('dataset.csv')

df.replace("", np.nan, inplace=True)

In [13]:
df = df.iloc[4:]

df.dropna(how='all', inplace=True)

new_columns = ['id', 'name', 'district', 'address', 'latitude', 'longitude', 'date', 'amount_LCD', 'amount_QR', 'type']

df.columns = new_columns

df.set_index('id', inplace=True)

# df.index = df.index.astype('int')

In [14]:

df['amount'] = df.apply(lambda row: row['amount_LCD'] if not pd.isna(row['amount_LCD']) else row['amount_QR'], axis=1)

df.drop(['amount_LCD', 'amount_QR'], axis=1, inplace=True)

df.index = df.index.astype('int')

In [15]:
year_counts = df['date'].str.extract(r'(\d{4})', expand=False).value_counts().sort_index()

for year, count in year_counts.iteritems():
    print(f'{year}: {count}')

2015: 132
2016: 281
2017: 736
2018: 313
2019: 21
2020: 664
2021: 5

/tmp/ipykernel_137034/1303792692.py:3: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for year, count in year_counts.iteritems():

In [16]:
df

,name,district,address,latitude,longitude,date,type,amount
id,,,,,,,,
301,경복궁역 7번출구 앞,종로구,서울특별시 종로구 사직로 지하130,37.575794,126.971451,2015-10-07,LCD,16
302,경복궁역 4번출구 뒤,종로구,서울특별시 종로구 사직로 지하130,37.575947,126.974060,2015-10-07,LCD,12
303,광화문역 1번출구 앞,종로구,서울특별시 종로구 세종대로 지하189,37.571770,126.974663,2015-10-07,LCD,8
304,광화문역 2번출구 앞,종로구,서울특별시 종로구 세종대로 지하172,37.572113,126.977577,2021-01-26,QR,7
305,종로구청 옆,종로구,서울특별시 종로구 삼봉로 43,37.572582,126.978355,2015-10-07,LCD,16
...,...,...,...,...,...,...,...,...
1085,래미안 솔베뉴(고덕로),강동구,양재대로1650,37.554569,127.145874,2020-01-13,QR,20
1086,래미안 솔베뉴(구천면로),강동구,양재대로1650,37.550598,127.145454,2020-01-10,QR,10
1088,풍납사거리(강동),강동구,성내동451-3,37.528122,127.119522,2020-01-14,QR,12
1089,고덕 래미안힐스테이트(201동),강동구,고덕동 675,37.560600,127.146698,2020-01-13,QR,10
1090,상일동역 2번출구 앞,강동구,고덕로 333,37.556789,127.166145,2020-01-13,QR,10